# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia -e  'using Pkg; Pkg.build()'
- DCAUTILS_TESTING=true julia --check-bounds=yes -e 'using Pkg; Pkg.test("GaussDCA"; coverage=true)'
- DCAUTILS_TESTING=true julia --check-bounds=yes --code-coverage=user -e 'using Pkg; Pkg.add("Compat"); using Compat; using Distributed; addprocs(2;exeflags=["--check-bounds=yes", "--code-coverage=user"]); cd("test"); include("runtests.jl")'
after_success:
- julia -e 'using Pkg; using GaussDCA; Pkg.add("Coverage"); using Coverage; get(ENV,"TRAVIS_OS_NAME","")=="linux" && Codecov.submit(Codecov.process_folder())'
