# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("GaussDCA")'
  - GDCA_TESTING=true julia --check-bounds=yes --inline=no -e 'Pkg.test("GaussDCA"; coverage=true)'
  - GDCA_TESTING=true julia --check-bounds=yes --inline=no --code-coverage=user -e 'addprocs(2; exeflags=["--check-bounds=yes", "--inline=no", "--code-coverage=user"]); cd(Pkg.dir("GaussDCA", "test")); include("runtests.jl")'
after_success:
  - julia -e 'Pkg.add("Coverage", v"0.3")'
  - julia -e 'cd(Pkg.dir("GaussDCA")); include("coverage.jl")'
