environment:
  matrix:
  - julia_version: 1.0
  - julia_version: 1.3
  - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit

matrix:
  allow_failures:
    - julia_version: latest

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

branches:
  only:
    - master
    - /release-.*/

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia --check-bounds=yes -e "if VERSION >= v\"0.7.0-DEV.5183\"; using Pkg; end; Pkg.add(\"Compat\"); using Compat.Distributed; addprocs(2; exeflags=[\"--check-bounds=yes\"]); cd(\"test\"); include(\"runtests.jl\")"
